### ISSUE TITLE
오타 발견했습니다.

### ISSUE THREAD

**Issue by gudwns1215** [revsic/ml-papers#1]
[https://github.com/revsic/ml-papers/blob/master/tts/melgan.md#1-introduction](url)의 
... 또한 short-term, long-term 등 서로 달느 timescale에서 ...
-> ... 또한 short-term, long-term 등 서로 다른 timescale에서 ... 
으로 바꿔야할것같네요

**Comment by revsic** [comment]
수정했습니다~ revsic@0cdebcf1777efddfb64dce1cb767644799af31f7
